/*
Copyright 2018 The sds cluster Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/samsung-cnct/cluster-manager-api/pkg/apis/cma/v1alpha1"
	"github.com/samsung-cnct/cluster-manager-api/pkg/client/clientset/versioned/scheme"
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	rest "k8s.io/client-go/rest"
)

type CmaV1alpha1Interface interface {
	RESTClient() rest.Interface
	SDSApplicationsGetter
	SDSClustersGetter
	SDSPackageManagersGetter
}

// CmaV1alpha1Client is used to interact with features provided by the cma.sds.samsung.com group.
type CmaV1alpha1Client struct {
	restClient rest.Interface
}

func (c *CmaV1alpha1Client) SDSApplications(namespace string) SDSApplicationInterface {
	return newSDSApplications(c, namespace)
}

func (c *CmaV1alpha1Client) SDSClusters(namespace string) SDSClusterInterface {
	return newSDSClusters(c, namespace)
}

func (c *CmaV1alpha1Client) SDSPackageManagers(namespace string) SDSPackageManagerInterface {
	return newSDSPackageManagers(c, namespace)
}

// NewForConfig creates a new CmaV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*CmaV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &CmaV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new CmaV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *CmaV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new CmaV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *CmaV1alpha1Client {
	return &CmaV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *CmaV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
