/*
Copyright 2018 Samsung SDS Cloud Native Computing Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/samsung-cnct/cluster-manager-api/pkg/apis/cma/v1alpha1"
	scheme "github.com/samsung-cnct/cluster-manager-api/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SDSPackageManagersGetter has a method to return a SDSPackageManagerInterface.
// A group's client should implement this interface.
type SDSPackageManagersGetter interface {
	SDSPackageManagers(namespace string) SDSPackageManagerInterface
}

// SDSPackageManagerInterface has methods to work with SDSPackageManager resources.
type SDSPackageManagerInterface interface {
	Create(*v1alpha1.SDSPackageManager) (*v1alpha1.SDSPackageManager, error)
	Update(*v1alpha1.SDSPackageManager) (*v1alpha1.SDSPackageManager, error)
	UpdateStatus(*v1alpha1.SDSPackageManager) (*v1alpha1.SDSPackageManager, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SDSPackageManager, error)
	List(opts v1.ListOptions) (*v1alpha1.SDSPackageManagerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SDSPackageManager, err error)
	SDSPackageManagerExpansion
}

// sDSPackageManagers implements SDSPackageManagerInterface
type sDSPackageManagers struct {
	client rest.Interface
	ns     string
}

// newSDSPackageManagers returns a SDSPackageManagers
func newSDSPackageManagers(c *CmaV1alpha1Client, namespace string) *sDSPackageManagers {
	return &sDSPackageManagers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sDSPackageManager, and returns the corresponding sDSPackageManager object, and an error if there is any.
func (c *sDSPackageManagers) Get(name string, options v1.GetOptions) (result *v1alpha1.SDSPackageManager, err error) {
	result = &v1alpha1.SDSPackageManager{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sdspackagemanagers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SDSPackageManagers that match those selectors.
func (c *sDSPackageManagers) List(opts v1.ListOptions) (result *v1alpha1.SDSPackageManagerList, err error) {
	result = &v1alpha1.SDSPackageManagerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sdspackagemanagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sDSPackageManagers.
func (c *sDSPackageManagers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sdspackagemanagers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a sDSPackageManager and creates it.  Returns the server's representation of the sDSPackageManager, and an error, if there is any.
func (c *sDSPackageManagers) Create(sDSPackageManager *v1alpha1.SDSPackageManager) (result *v1alpha1.SDSPackageManager, err error) {
	result = &v1alpha1.SDSPackageManager{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sdspackagemanagers").
		Body(sDSPackageManager).
		Do().
		Into(result)
	return
}

// Update takes the representation of a sDSPackageManager and updates it. Returns the server's representation of the sDSPackageManager, and an error, if there is any.
func (c *sDSPackageManagers) Update(sDSPackageManager *v1alpha1.SDSPackageManager) (result *v1alpha1.SDSPackageManager, err error) {
	result = &v1alpha1.SDSPackageManager{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sdspackagemanagers").
		Name(sDSPackageManager.Name).
		Body(sDSPackageManager).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *sDSPackageManagers) UpdateStatus(sDSPackageManager *v1alpha1.SDSPackageManager) (result *v1alpha1.SDSPackageManager, err error) {
	result = &v1alpha1.SDSPackageManager{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sdspackagemanagers").
		Name(sDSPackageManager.Name).
		SubResource("status").
		Body(sDSPackageManager).
		Do().
		Into(result)
	return
}

// Delete takes name of the sDSPackageManager and deletes it. Returns an error if one occurs.
func (c *sDSPackageManagers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sdspackagemanagers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sDSPackageManagers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sdspackagemanagers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched sDSPackageManager.
func (c *sDSPackageManagers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SDSPackageManager, err error) {
	result = &v1alpha1.SDSPackageManager{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sdspackagemanagers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
