/*
Copyright 2018 Samsung SDS Cloud Native Computing Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	cma_v1alpha1 "github.com/samsung-cnct/cluster-manager-api/pkg/apis/cma/v1alpha1"
	versioned "github.com/samsung-cnct/cluster-manager-api/pkg/client/clientset/versioned"
	internalinterfaces "github.com/samsung-cnct/cluster-manager-api/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/samsung-cnct/cluster-manager-api/pkg/client/listers/cma/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SDSApplicationInformer provides access to a shared informer and lister for
// SDSApplications.
type SDSApplicationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SDSApplicationLister
}

type sDSApplicationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSDSApplicationInformer constructs a new informer for SDSApplication type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSDSApplicationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSDSApplicationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSDSApplicationInformer constructs a new informer for SDSApplication type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSDSApplicationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CmaV1alpha1().SDSApplications(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CmaV1alpha1().SDSApplications(namespace).Watch(options)
			},
		},
		&cma_v1alpha1.SDSApplication{},
		resyncPeriod,
		indexers,
	)
}

func (f *sDSApplicationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSDSApplicationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sDSApplicationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cma_v1alpha1.SDSApplication{}, f.defaultInformer)
}

func (f *sDSApplicationInformer) Lister() v1alpha1.SDSApplicationLister {
	return v1alpha1.NewSDSApplicationLister(f.Informer().GetIndexer())
}
