/*
Copyright 2018 Samsung SDS Cloud Native Computing Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/samsung-cnct/cluster-manager-api/pkg/apis/cma/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSDSClusters implements SDSClusterInterface
type FakeSDSClusters struct {
	Fake *FakeCmaV1alpha1
	ns   string
}

var sdsclustersResource = schema.GroupVersionResource{Group: "cma.sds.samsung.com", Version: "v1alpha1", Resource: "sdsclusters"}

var sdsclustersKind = schema.GroupVersionKind{Group: "cma.sds.samsung.com", Version: "v1alpha1", Kind: "SDSCluster"}

// Get takes name of the sDSCluster, and returns the corresponding sDSCluster object, and an error if there is any.
func (c *FakeSDSClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.SDSCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sdsclustersResource, c.ns, name), &v1alpha1.SDSCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDSCluster), err
}

// List takes label and field selectors, and returns the list of SDSClusters that match those selectors.
func (c *FakeSDSClusters) List(opts v1.ListOptions) (result *v1alpha1.SDSClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sdsclustersResource, sdsclustersKind, c.ns, opts), &v1alpha1.SDSClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SDSClusterList{ListMeta: obj.(*v1alpha1.SDSClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.SDSClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sDSClusters.
func (c *FakeSDSClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sdsclustersResource, c.ns, opts))

}

// Create takes the representation of a sDSCluster and creates it.  Returns the server's representation of the sDSCluster, and an error, if there is any.
func (c *FakeSDSClusters) Create(sDSCluster *v1alpha1.SDSCluster) (result *v1alpha1.SDSCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sdsclustersResource, c.ns, sDSCluster), &v1alpha1.SDSCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDSCluster), err
}

// Update takes the representation of a sDSCluster and updates it. Returns the server's representation of the sDSCluster, and an error, if there is any.
func (c *FakeSDSClusters) Update(sDSCluster *v1alpha1.SDSCluster) (result *v1alpha1.SDSCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sdsclustersResource, c.ns, sDSCluster), &v1alpha1.SDSCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDSCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSDSClusters) UpdateStatus(sDSCluster *v1alpha1.SDSCluster) (*v1alpha1.SDSCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sdsclustersResource, "status", c.ns, sDSCluster), &v1alpha1.SDSCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDSCluster), err
}

// Delete takes name of the sDSCluster and deletes it. Returns an error if one occurs.
func (c *FakeSDSClusters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sdsclustersResource, c.ns, name), &v1alpha1.SDSCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSDSClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sdsclustersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SDSClusterList{})
	return err
}

// Patch applies the patch and returns the patched sDSCluster.
func (c *FakeSDSClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SDSCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sdsclustersResource, c.ns, name, data, subresources...), &v1alpha1.SDSCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDSCluster), err
}
