/*
Copyright 2018 The sds cluster Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/samsung-cnct/cluster-manager-api/pkg/apis/cma/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSDSApplications implements SDSApplicationInterface
type FakeSDSApplications struct {
	Fake *FakeCmaV1alpha1
	ns   string
}

var sdsapplicationsResource = schema.GroupVersionResource{Group: "cma.sds.samsung.com", Version: "v1alpha1", Resource: "sdsapplications"}

var sdsapplicationsKind = schema.GroupVersionKind{Group: "cma.sds.samsung.com", Version: "v1alpha1", Kind: "SDSApplication"}

// Get takes name of the sDSApplication, and returns the corresponding sDSApplication object, and an error if there is any.
func (c *FakeSDSApplications) Get(name string, options v1.GetOptions) (result *v1alpha1.SDSApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sdsapplicationsResource, c.ns, name), &v1alpha1.SDSApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDSApplication), err
}

// List takes label and field selectors, and returns the list of SDSApplications that match those selectors.
func (c *FakeSDSApplications) List(opts v1.ListOptions) (result *v1alpha1.SDSApplicationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sdsapplicationsResource, sdsapplicationsKind, c.ns, opts), &v1alpha1.SDSApplicationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SDSApplicationList{}
	for _, item := range obj.(*v1alpha1.SDSApplicationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sDSApplications.
func (c *FakeSDSApplications) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sdsapplicationsResource, c.ns, opts))

}

// Create takes the representation of a sDSApplication and creates it.  Returns the server's representation of the sDSApplication, and an error, if there is any.
func (c *FakeSDSApplications) Create(sDSApplication *v1alpha1.SDSApplication) (result *v1alpha1.SDSApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sdsapplicationsResource, c.ns, sDSApplication), &v1alpha1.SDSApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDSApplication), err
}

// Update takes the representation of a sDSApplication and updates it. Returns the server's representation of the sDSApplication, and an error, if there is any.
func (c *FakeSDSApplications) Update(sDSApplication *v1alpha1.SDSApplication) (result *v1alpha1.SDSApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sdsapplicationsResource, c.ns, sDSApplication), &v1alpha1.SDSApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDSApplication), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSDSApplications) UpdateStatus(sDSApplication *v1alpha1.SDSApplication) (*v1alpha1.SDSApplication, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sdsapplicationsResource, "status", c.ns, sDSApplication), &v1alpha1.SDSApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDSApplication), err
}

// Delete takes name of the sDSApplication and deletes it. Returns an error if one occurs.
func (c *FakeSDSApplications) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sdsapplicationsResource, c.ns, name), &v1alpha1.SDSApplication{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSDSApplications) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sdsapplicationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SDSApplicationList{})
	return err
}

// Patch applies the patch and returns the patched sDSApplication.
func (c *FakeSDSApplications) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SDSApplication, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sdsapplicationsResource, c.ns, name, data, subresources...), &v1alpha1.SDSApplication{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDSApplication), err
}
